Spring:
  application:
    name: zuulServer
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /greyson
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false